# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .nat_instance import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "fcknat",
  "mod": "index",
  "fqn": "pierskarsenbarg_pulumi_fcknat",
  "classes": {
   "fcknat:index:NatInstance": "NatInstance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "fcknat",
  "token": "pulumi:providers:fcknat",
  "fqn": "pierskarsenbarg_pulumi_fcknat",
  "class": "Provider"
 }
]
"""
)
